name: Feature request
description: Suggest an idea for ViMusic
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        **1- I've checked that there is no other issue about this feature request.**
        **2- This issue contains only one feature request.**
        **3- The title of this issue accurately describes the feature request.**

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: What feature you want the app to have? Provide detailed description about what it should look like or where it should be added.
    validations:
      required: true

  - type: textarea
    id: why-is-the-feature-requested
    attributes:
      label: Why do you want this feature?
      description: Describe the problem or limitation that motivates you to want this feature to be added.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Add any other context or screenshots about the feature request here.
      placeholder: |
        Additional details and attachments.
